/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lentrix.pharmapos.modules;

import com.lentrix.pharmapos.models.Item;
import com.lentrix.pharmapos.models.User;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lentrix
 */
public class ManageItemsModule extends javax.swing.JFrame {

    private User user;
    private JFrame mainFrame;
    private Item selectedItem;
    private LinkedList<Item> items;
    /**
     * Creates new form ManageItemsModule
     */
    public ManageItemsModule(JFrame mainFrame, User user) {
        initComponents();
        this.user = user;
        this.mainFrame = mainFrame;
        setExtendedState(MAXIMIZED_BOTH);
        refreshTable();
    }

    private void refreshTable() {
        try {
            items = Item.getItems(filterNameField.getText());
            int rows = items.size();
            
            Object[][] content = new Object[rows][4];
            String[] headers = {"Name","Generic Name", "Manufacturer","Discount Rate"};
            
            for(int i=0; i<rows; i++) {
                Item item = items.get(i);
                content[i][0] = item;
                content[i][1] = item.getGeneric();
                content[i][2] = item.getManufacturer();
                content[i][3] = (item.getDisc()*100) + "%";
            }
            
            DefaultTableModel model = new DefaultTableModel(content, headers) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            
            jTable1.setModel(model);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(50);
            
        }catch(SQLException ex) {
            Helper.error(this, ex.getMessage());
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        barcodeSearchField = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(20, 70), new java.awt.Dimension(30, 32767));
        jLabel10 = new javax.swing.JLabel();
        filterNameField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        genericNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        barCodeField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        manufacturerField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        newButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        discountRateField = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MDS - Manage Items");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/mdslogomin.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/basket64.png"))); // NOI18N
        jLabel2.setText("Manage Items");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));

        jPanel4.setBackground(new java.awt.Color(254, 254, 254));

        jLabel11.setText("Search Bar Code:");
        jPanel4.add(jLabel11);

        barcodeSearchField.setPreferredSize(new java.awt.Dimension(200, 27));
        barcodeSearchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                barcodeSearchFieldFocusGained(evt);
            }
        });
        barcodeSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeSearchFieldActionPerformed(evt);
            }
        });
        jPanel4.add(barcodeSearchField);

        jPanel3.add(jPanel4);
        jPanel3.add(filler1);

        jLabel10.setText("Filter Name:");
        jPanel3.add(jLabel10);

        filterNameField.setPreferredSize(new java.awt.Dimension(200, 27));
        filterNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterNameFieldActionPerformed(evt);
            }
        });
        jPanel3.add(filterNameField);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(52, 52, 52));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 350));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 230));
        jLabel3.setText("Item Details:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 230));
        jLabel4.setText("Name:");

        nameField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 230));
        jLabel5.setText("Generic Name:");

        genericNameField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 230));
        jLabel6.setText("Bar Code:");

        barCodeField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 230));
        jLabel7.setText("Manufacturer:");

        manufacturerField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 230));
        jLabel8.setText("Discountable Rate:");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 231, 0));
        jLabel9.setText("?");
        jLabel9.setToolTipText("Write in decimal values e.g. 0.01 for 1%");

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/new32.png"))); // NOI18N
        newButton.setText("New");
        newButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/save32.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.setToolTipText("Save Item Details");
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        discountRateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0.##"))));
        discountRateField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        discountRateField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField)
                    .addComponent(genericNameField)
                    .addComponent(barCodeField)
                    .addComponent(manufacturerField)
                    .addComponent(discountRateField)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 156, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genericNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manufacturerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discountRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jTable1.setFont(new java.awt.Font("NanumGothic", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1224, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        selectedItem = null;
        nameField.setText(null);
        genericNameField.setText(null);
        barCodeField.setText(null);
        manufacturerField.setText(null);
        discountRateField.setText(null);
        nameField.grabFocus();
    }//GEN-LAST:event_newButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        mainFrame.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void filterNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterNameFieldActionPerformed
        refreshTable();
    }//GEN-LAST:event_filterNameFieldActionPerformed

    private boolean validateEntry() {
        return !nameField.getText().isEmpty()
                && !genericNameField.getText().isEmpty()
                && !barCodeField.getText().isEmpty()
                && !manufacturerField.getText().isEmpty()
                && !discountRateField.getText().isEmpty();
    }
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(!validateEntry()) {
            Helper.error(this, "There is an error in your entry."
                    + "\nPlease check and make sure no field is empty.");
            return;
        }
        try {
            if(selectedItem==null) {
                selectedItem = new Item(
                        -1, nameField.getText(), genericNameField.getText(), 
                        barCodeField.getText(), manufacturerField.getText(),
                        Float.valueOf(discountRateField.getText())

                );
            }else {
                selectedItem.setName(nameField.getText());
                selectedItem.setGeneric(genericNameField.getText());
                selectedItem.setBarCode(barCodeField.getText());
                selectedItem.setManufacturer(manufacturerField.getText());
                selectedItem.setDisc(Float.valueOf(discountRateField.getText()));
            }
            selectedItem.save();
            Helper.info(this, "The item has been saved successfully!");
            refreshTable();
        }catch(SQLException ex) {
            Helper.error(this, ex.getMessage());
            ex.printStackTrace();
        }catch(NumberFormatException ex) {
            Helper.error(this, "Invalid entry for a numeric field.");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        selectedItem = (Item)jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        refreshForm();
    }//GEN-LAST:event_jTable1MouseClicked

    private void barcodeSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeSearchFieldActionPerformed
        String barCode = barcodeSearchField.getText();
        
        for(int i=0; i<items.size(); i++) {
            Item itm = items.get(i);
            if(itm.getBarCode().equals(barCode)){
                selectedItem = itm;
                refreshForm();
                return;
            }
        }
        Helper.error(this, "Bar Code not found on the records!");
    }//GEN-LAST:event_barcodeSearchFieldActionPerformed

    private void barcodeSearchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_barcodeSearchFieldFocusGained
        barcodeSearchField.setSelectionStart(0);
        barcodeSearchField.setSelectionEnd(barcodeSearchField.getText().length());
    }//GEN-LAST:event_barcodeSearchFieldFocusGained

    private void refreshForm() {
        nameField.setText(selectedItem.getName());
        genericNameField.setText(selectedItem.getGeneric());
        barCodeField.setText(selectedItem.getBarCode());
        manufacturerField.setText(selectedItem.getManufacturer());
        discountRateField.setText(String.valueOf(selectedItem.getDisc()));
        nameField.grabFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barCodeField;
    private javax.swing.JTextField barcodeSearchField;
    private javax.swing.JFormattedTextField discountRateField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField filterNameField;
    private javax.swing.JTextField genericNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField manufacturerField;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton newButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
