/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lentrix.pharmapos.modules;

import com.lentrix.pharmapos.models.Stock;
import com.lentrix.pharmapos.models.User;
import java.awt.GraphicsEnvironment;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lentrix
 */
public class ManageStocksModule extends javax.swing.JDialog {
    private LinkedList<Stock> stocks;
    private Stock selectedStock;
    private User user;
    /**
     * Creates new form ManageStocksModule
     */
    public ManageStocksModule(java.awt.Frame parent, boolean modal, User user) {
        super(parent, modal);
        this.user = user;
        initComponents();
        setBounds(GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds()); 
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 70), new java.awt.Dimension(30, 32767));
        jLabel10 = new javax.swing.JLabel();
        filterNameField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        genericNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        remainingField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        purchaseAmountField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sellingPriceField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        auditingField = new javax.swing.JTextArea();
        updateButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Stocks");

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/mdslogomin.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/managestock64.png"))); // NOI18N
        jLabel2.setText("Manage Stocks");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.add(filler1);

        jLabel10.setText("Filter Name:");
        jPanel3.add(jLabel10);

        filterNameField.setPreferredSize(new java.awt.Dimension(250, 27));
        filterNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterNameFieldActionPerformed(evt);
            }
        });
        filterNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filterNameFieldKeyPressed(evt);
            }
        });
        jPanel3.add(filterNameField);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(50, 50, 50));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Stock Details:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Name:");

        nameField.setEditable(false);
        nameField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Generic Name:");

        genericNameField.setEditable(false);
        genericNameField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Quantity:");

        quantityField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        quantityField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Remaining:");

        remainingField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        remainingField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Purchase Amount:");

        purchaseAmountField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        purchaseAmountField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Selling Price Per Unit:");

        sellingPriceField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        sellingPriceField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        auditingField.setEditable(false);
        auditingField.setBackground(new java.awt.Color(207, 207, 207));
        auditingField.setColumns(20);
        auditingField.setLineWrap(true);
        auditingField.setRows(3);
        auditingField.setText("Stocked by Benjie on Nov-15-2016\nlast updated by Benjie on Nov-15-2016.");
        auditingField.setWrapStyleWord(true);
        auditingField.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jScrollPane1.setViewportView(auditingField);

        updateButton.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/save32.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(remainingField)
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(genericNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(purchaseAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(sellingPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genericNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remainingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purchaseAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellingPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1014, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void filterNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterNameFieldActionPerformed
        refreshTable();
    }//GEN-LAST:event_filterNameFieldActionPerformed

    private void filterNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterNameFieldKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_DOWN) {
            jTable1.grabFocus();
        }
    }//GEN-LAST:event_filterNameFieldKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        selectedStock = stocks.get(index);
        updateForm();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER) {
            int index = jTable1.getSelectedRow();
            selectedStock = stocks.get(index);
            updateForm();
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            if(selectedStock==null) {
                throw new SQLException("No stock is currently selected.");
            }
            selectedStock.setQuantity(Integer.parseInt(quantityField.getText()));
            selectedStock.setRemaining(Integer.parseInt(remainingField.getText()));
            selectedStock.setPurchaseAmount(Float.parseFloat(purchaseAmountField.getText()));
            selectedStock.setPrice(Float.parseFloat(sellingPriceField.getText()));
            selectedStock.save(user);
            Helper.info(this, "The stock has been updated successfully!");
            refreshTable();
        }catch(NumberFormatException ex) {
            Helper.error(this, "Invalid entry of numeric field.");
            ex.printStackTrace();
        }catch(SQLException ex) {
            Helper.error(this, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void updateForm() {
        nameField.setText(selectedStock.getItem().getName());
        genericNameField.setText(selectedStock.getItem().getGeneric());
        quantityField.setText(String.valueOf(selectedStock.getQuantity()));
        remainingField.setText(String.valueOf(selectedStock.getRemaining()));
        purchaseAmountField.setText(String.valueOf(selectedStock.getPurchaseAmount()));
        sellingPriceField.setText(String.valueOf(selectedStock.getPrice()));
        auditingField.setText("Stocked by " + selectedStock.getStockedBy().getFullName()
                + " on " + Helper.formatSQLDateFull(selectedStock.getDate()) + "\n"
                + " last updated by " + selectedStock.getUpdatedBy().getFullName() + " on "
                + Helper.formatSQLDateFull(selectedStock.getUpdatedDate())
        );
        quantityField.grabFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea auditingField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField filterNameField;
    private javax.swing.JTextField genericNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField purchaseAmountField;
    private javax.swing.JTextField quantityField;
    private javax.swing.JTextField remainingField;
    private javax.swing.JTextField sellingPriceField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
        try {
            stocks = Stock.search(filterNameField.getText());
            int rows = stocks.size();
            Object[][] content = new Object[rows][5];
            String[] header = {"Name", "Generic", "Date Stocked", "Quantity", "Remaining"};
            for(int i=0; i<rows; i++) {
                
                Stock s = stocks.get(i);
                
                content[i][0] = s.getItem().getName();
                content[i][1] = s.getItem().getGeneric();
                content[i][2] = Helper.formatSQLDate(s.getDate());
                content[i][3] = s.getQuantity();
                content[i][4] = s.getRemaining();
            }
            
            DefaultTableModel model = new DefaultTableModel(content, header) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
                
            };
            
            jTable1.setModel(model);
        }catch(SQLException ex) {
            Helper.error(this, ex.getMessage());
            ex.printStackTrace();
        }
    }
}
