/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lentrix.pharmapos.modules;

import com.lentrix.pharmapos.models.CartItem;
import com.lentrix.pharmapos.models.Sales;
import com.lentrix.pharmapos.models.SalesItem;
import com.lentrix.pharmapos.models.Stock;
import com.lentrix.pharmapos.models.User;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lentrix
 */
public class POSTerminal extends javax.swing.JFrame {
    private javax.swing.JFrame parent;
    private User user;
    private LinkedList<CartItem> cart;
    private CartItem selectedItem;
    private LinkedList<Stock> stockSearchResults;
    /**
     * Creates new form POSTerminal
     * @param parent
     */
    public POSTerminal(javax.swing.JFrame parent, User user) {
        initComponents();
        
        barCodeField.addKeyListener(new POSKeyListener());
        
        this.parent = parent;
        this.user = user;
        cart = new LinkedList<>();
        stockSearchResults = new LinkedList<>();
        selectedItem = null;
        
        refreshStatus();
        
        initSales();
        super.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    private void initSales() {
        cart.clear();
        finishButton.setEnabled(false);
        cancelButton.setEnabled(false);
        //set Date field
        java.sql.Date dt = java.sql.Date.valueOf(LocalDate.now(ZoneId.systemDefault()));
        dateField.setText(dt.toString());
        
        refreshTable();
        barCodeField.grabFocus();
    }
    
    private void refreshTable(){
        String headers[] = {"Item", "Generic Name", "Price", "Qty", "Discount", "Amount"};
        int rows = cart.size();
        Object content[][] = new Object[rows][headers.length];
        
        if(rows>0) {
            float total = 0.0f;
            for(int i=0; i<rows; i++) {
                CartItem ci = cart.get(i);
                content[i][0] = ci.getStock().getItem().getName();
                content[i][1] = ci.getStock().getItem().getGeneric();
                content[i][2] = String.format("%.2f",ci.getStock().getPrice());
                content[i][3] = ci.getQty();
                content[i][4] = String.format("%.2f", ci.getDiscountAmount());
                content[i][5] = String.format("%.2f", ci.getFinalAmount());
                total += ci.getFinalAmount();
            }
            
            totalLabel.setText(String.format("Php %.2f", total));
            finishButton.setEnabled(true);
            cancelButton.setEnabled(true);
        }else {
            finishButton.setEnabled(false);
            cancelButton.setEnabled(false);
            totalLabel.setText("Php 0.00");
        }
        
        DefaultTableModel model = new DefaultTableModel(content, headers) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        jTable1.setModel(model);
        jTable1.getColumnModel().getColumn(0).setMinWidth(200);
        jTable1.getColumnModel().getColumn(1).setMinWidth(200);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(40);
        
        jTable1.getColumnModel().getColumn(2).setCellRenderer(Helper.getRightRender());
        jTable1.getColumnModel().getColumn(3).setCellRenderer(Helper.getCenterRender());
        jTable1.getColumnModel().getColumn(4).setCellRenderer(Helper.getRightRender());
        jTable1.getColumnModel().getColumn(5).setCellRenderer(Helper.getRightRender());
    }
    
    private void addToCart(Stock stock, int qty) {
        CartItem cartItem = new CartItem(stock,qty,false);
        selectedItem = cartItem;
        cart.add(cartItem);
        searchField.setText(null);
        barCodeField.setText(null);
        stockSearchResults.clear();
        renderStockSearchResults();
        refreshTable();
        barCodeField.grabFocus();
    }
    
    private void addToCart(Stock stock) {
        addToCart(stock, 1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainButtonsPanel = new javax.swing.JPanel();
        finishButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        barCodeField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchList = new javax.swing.JList<>();
        jPanel9 = new javax.swing.JPanel();
        transactionsTodayLabel = new javax.swing.JLabel();
        userIDLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dateField = new javax.swing.JFormattedTextField();
        jButton6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MDS Point of Sale");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setPreferredSize(new java.awt.Dimension(80, 80));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/mdslogomin.png"))); // NOI18N
        jPanel2.add(jLabel1, java.awt.BorderLayout.WEST);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/pos64.png"))); // NOI18N
        jLabel2.setText(" Point of Sale Terminal");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        mainButtonsPanel.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        finishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/save32.png"))); // NOI18N
        finishButton.setText("Finish");
        finishButton.setEnabled(false);
        finishButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        finishButton.setPreferredSize(new java.awt.Dimension(100, 100));
        finishButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });
        mainButtonsPanel.add(finishButton);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/cancel_32.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setEnabled(false);
        cancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelButton.setPreferredSize(new java.awt.Dimension(100, 100));
        cancelButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        mainButtonsPanel.add(cancelButton);

        jPanel2.add(mainButtonsPanel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(66, 66, 66));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bar Code Entry"));

        barCodeField.setFont(new java.awt.Font("DejaVu Sans Semi-Condensed", 0, 18)); // NOI18N
        barCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barCodeFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barCodeField)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search Entry"));

        searchField.setFont(new java.awt.Font("DejaVu Sans Semi-Condensed", 0, 18)); // NOI18N
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFieldKeyPressed(evt);
            }
        });

        searchList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchListKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(searchList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchField, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(1, 10, 78));
        jPanel9.setForeground(new java.awt.Color(112, 253, 243));

        transactionsTodayLabel.setForeground(new java.awt.Color(71, 252, 245));
        transactionsTodayLabel.setText("Transactions Today: ");

        userIDLabel.setForeground(new java.awt.Color(71, 252, 245));
        userIDLabel.setText("User ID: ");

        nameLabel.setForeground(new java.awt.Color(71, 252, 245));
        nameLabel.setText("Name:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transactionsTodayLabel)
                    .addComponent(userIDLabel)
                    .addComponent(nameLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transactionsTodayLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(66, 66, 66));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel5.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel5.setLayout(new java.awt.GridLayout(5, 1, 5, 5));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/f1.png"))); // NOI18N
        jButton1.setText("Change Qty");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/f2.png"))); // NOI18N
        jButton5.setText("Decrease Qty");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/f3.png"))); // NOI18N
        jButton4.setText("Increase Qty");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/f4.png"))); // NOI18N
        jButton2.setText("Remove Item");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel5.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lentrix/pharmapos/images/f5.png"))); // NOI18N
        jButton3.setText("Discount");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel5.add(jButton3);

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(147, 178, 197));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Semi-Condensed", 0, 18)); // NOI18N
        jLabel3.setText("Date:");

        dateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat(""))));
        dateField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dateField.setFont(new java.awt.Font("DejaVu Sans Semi-Condensed", 0, 18)); // NOI18N

        jButton6.setFont(new java.awt.Font("DejaVu Sans Semi-Condensed", 0, 14)); // NOI18N
        jButton6.setText("View Transaction History");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        totalLabel.setFont(new java.awt.Font("DejaVu Sans Semi-Condensed", 0, 48)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalLabel.setText("PhP 0.00");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans Semi-Condensed", 0, 48)); // NOI18N
        jLabel6.setText("TOTAL");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(406, Short.MAX_VALUE)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel6)
                    .addContainerGap(668, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalLabel)
                .addContainerGap())
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel6.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item", "Description", "Price", "Qty", "Discount", "Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(parent!=null) {
            parent.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void barCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barCodeFieldActionPerformed
        String barCode = barCodeField.getText();
        
        try {
            Stock stock = Stock.barCodeSearch(barCode);
            if(stock!=null) {
                addToCart(stock);
            }else {
                Helper.error(parent, "The bar code " + barCode + " does not exists");
            }
        }catch(SQLException ex) {
            Helper.error(parent, ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_barCodeFieldActionPerformed

    private void searchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyTyped
        if(!evt.isActionKey()) {
            try {
                stockSearchResults = Stock.search(searchField.getText() + evt.getKeyChar());
                //render the stockSearchResults to the list
                renderStockSearchResults();
            }catch(SQLException ex) {
                Helper.error(this, ex.getMessage());
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_searchFieldKeyTyped

    private void renderStockSearchResults() {
        String[] stockNames = new String[stockSearchResults.size()];
        for(int i=0; i<stockSearchResults.size(); i++) {
            stockNames[i] = stockSearchResults.get(i).toString();
        }
        searchList.setListData(stockNames);
    }
    
    private void searchListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchListKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER) {
            Stock s = stockSearchResults.get(searchList.getSelectedIndex());
            addToCart(s);
        }
    }//GEN-LAST:event_searchListKeyPressed

    private void searchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_DOWN || 
                evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER ) {
            searchList.grabFocus();
            searchList.setSelectedIndex(0);
        }
    }//GEN-LAST:event_searchFieldKeyPressed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancel();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        selectedItem = cart.get(selectedRow);
        barCodeField.grabFocus();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        changeQty();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        decreaseQty();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        increaseQty();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        finish();
    }//GEN-LAST:event_finishButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new TransactionHistory(this, true, user).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void changeQty() {
        if(selectedItem != null) {
            String entry = JOptionPane.showInputDialog(this, "Enter new quantity: ");
            try {
                int qty = Integer.parseInt(entry);
                int remaining = selectedItem.getStock().getRemaining();
                if(remaining>=qty) {
                    selectedItem.setQty(qty);
                }else {
                    int response = JOptionPane.showConfirmDialog(this, 
                            "This particular stock only has " 
                                    + remaining + " items remaining.\n"
                            + "I will attempt to add another item to cover for the remaining " 
                                    + (qty-remaining) + " items.",
                            "Add Row?", JOptionPane.YES_NO_OPTION);
                    selectedItem.setQty(remaining);
                    if(response==JOptionPane.YES_OPTION) {
                        Stock s = Stock.findNextAvailableStock2(selectedItem.getStock().getItem().getId());
                        addToCart(s, qty-remaining);
                    }
                }
                refreshTable();
            }catch(NumberFormatException ex) {
                Helper.error(this, "The quantity you entered\nis not a valid number.");
            }catch(SQLException ex) {
                Helper.error(this, ex.getMessage());
                ex.printStackTrace();
            }
        }else {
            Helper.error(this, "There is not item selected.");
        }
    }
    
    private void increaseQty() {
        if(selectedItem!=null) {
            if(selectedItem.getQty()<selectedItem.getStock().getRemaining()) {
                selectedItem.setQty(selectedItem.getQty()+1);
            }else {
                int response = JOptionPane.showConfirmDialog(this, "This action will exceed the remaining stock."
                        + "\nDo you want me to attempt to add another item?", "Add Item?", 
                        JOptionPane.YES_NO_OPTION);
                if(response==JOptionPane.YES_OPTION) {
                    try {
                        Stock s = Stock.findNextAvailableStock2(selectedItem.getStock().getItem().getId());
                        addToCart(s, 1);
                    }catch(SQLException ex) {
                        Helper.error(this, ex.getMessage());
                        ex.printStackTrace();
                    }
                }
            }
            refreshTable();
        }else {
            Helper.error(this, "There is not item selected.");
        }
    }
    
    private void decreaseQty() {
        if(selectedItem!=null && selectedItem.getQty()>1) {
            selectedItem.setQty(selectedItem.getQty()-1);
            refreshTable();
        }
    }
    
    private void removeItem() {
        if(selectedItem!=null) {
            int response = JOptionPane.showConfirmDialog(this, 
                    "Are you sure you want to remove this item?", "Remove?", 
                    JOptionPane.YES_NO_OPTION);
            if(response == JOptionPane.YES_OPTION) {
                cart.remove(selectedItem);
                selectedItem = null;
                refreshTable();
            }
        }else {
            Helper.error(this, "There is no item selected.");
        }
    }
    
    private void toggleDiscount() {
        if(selectedItem!=null) {
            
            selectedItem.setDiscounted(!selectedItem.isDiscounted());
            refreshTable();
            
        }else {
            Helper.error(this, "There is not item selected.");
        }
    }
    
    private void cancel() {
        int response = JOptionPane.showConfirmDialog(this, 
                "Are you sure about cancelling\nthis transaction?",
                "Cancel?",JOptionPane.YES_NO_OPTION);
        if(response==JOptionPane.YES_OPTION) {
            initSales();
        }
    }
    
    private void refreshStatus() {
        nameLabel.setText("Name: " + user.getFullName());
        userIDLabel.setText("User ID: " + user.getUser());
        try {
            java.sql.Date date = java.sql.Date.valueOf(LocalDate.now());
            int count = Sales.transactionCount(user, date);
            transactionsTodayLabel.setText("Transactions Today: " + count);
        }catch(SQLException ex) {
            Helper.error(this, ex.getMessage());
            ex.printStackTrace();
        }
    }
    
    private void finish() {
        try {
            java.sql.Date date = java.sql.Date.valueOf(dateField.getText());
            String entry = JOptionPane.showInputDialog(this, "Enter cash tender: ");
            if(entry==null) {
                return;
            }
            float cash = Float.parseFloat(entry);
            Sales sales = new Sales(-1, date, user, cash);
            sales.save();
            
            float total = 0f;
            for(int i=0; i<cart.size(); i++) {
                CartItem c = cart.get(i);
                SalesItem si = new SalesItem(-1,sales,c.getStock(),c.getQty(), 
                        c.getStock().getPrice(),c.getDiscountAmount());
                si.save();
                c.getStock().shellOut(c.getQty());
                total+=c.getFinalAmount();
            }
            
            Helper.info(this, "Transaction completed."
                    + "\nChange: " + String.format("%.2f", cash-total));
            
            refreshStatus();
            cart.clear();
            initSales();
        }catch(SQLException ex) {
            Helper.error(this, ex.getMessage());
            ex.printStackTrace();
        }catch(NumberFormatException ex) {
            Helper.error(this, "You entered an invalid amount for cash tender.");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barCodeField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JFormattedTextField dateField;
    private javax.swing.JButton finishButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainButtonsPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField searchField;
    private javax.swing.JList<String> searchList;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel transactionsTodayLabel;
    private javax.swing.JLabel userIDLabel;
    // End of variables declaration//GEN-END:variables

    class POSKeyListener extends java.awt.event.KeyAdapter {

        @Override
        public void keyPressed(KeyEvent e) {
            if(e.isActionKey()) {
                switch(e.getKeyCode()) {
                    case java.awt.event.KeyEvent.VK_F1 : changeQty(); break;
                    case java.awt.event.KeyEvent.VK_F2 : decreaseQty(); break;
                    case java.awt.event.KeyEvent.VK_F3 : increaseQty(); break;
                    case java.awt.event.KeyEvent.VK_F4 : removeItem(); break;
                    case java.awt.event.KeyEvent.VK_F5 : toggleDiscount(); break;
                    case java.awt.event.KeyEvent.VK_ESCAPE : cancel(); break;
                    case java.awt.event.KeyEvent.VK_F12 : finish(); break;
                    
                }
            }
        }
        
    }
}