/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lentrix.pharmapos.modules;

import com.lentrix.pharmapos.models.Sales;
import com.lentrix.pharmapos.models.SalesItem;
import com.lentrix.pharmapos.models.User;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lentrix
 */
public class TransactionHistory extends javax.swing.JDialog {
    private LinkedList<Sales> sales;
    private Sales selectedSales;
    private final User user;
    /**
     * Creates new form TransactionHistory
     * @param parent The parent window
     * @param modal whether modal or not
     * @param user The user relating to this Transaction History
     */
    public TransactionHistory(java.awt.Frame parent, boolean modal, User user) {
        super(parent, modal);
        this.user = user;
        initComponents();
        userLabel.setText("User: "+user.getFullName());
        
        java.sql.Date date = java.sql.Date.valueOf(LocalDate.now());
        fromField.setText(date.toString());
        toField.setText(date.toString());
        refreshTable();
    }
    
    private void refreshTable() {
        try {
            java.sql.Date fr = java.sql.Date.valueOf(fromField.getText());
            java.sql.Date to = java.sql.Date.valueOf(toField.getText());
            sales = Sales.loadHistory(user, fr, to);
            
            String headers[] = {"Date","Invoice#", "Amount", "Cash Tender"};
            Object content[][] = new Object[sales.size()][headers.length];
            
            for(int i=0; i<sales.size(); i++) {
                Sales s = sales.get(i);
                content[i][0] = Helper.formatSQLDateFull(s.getDate());
                content[i][1] = String.format("%010d", s.getId());
                content[i][2] = String.format("%.2f",s.getTotalAmount());
                content[i][3] = String.format("%.2f",s.getCashTender());
            }
            
            DefaultTableModel model = new DefaultTableModel(content, headers) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }                
            };
            
            salesTable.setModel(model);
            salesTable.getColumnModel().getColumn(2).setCellRenderer(Helper.getRightRender());
            salesTable.getColumnModel().getColumn(3).setCellRenderer(Helper.getRightRender());
        }catch(SQLException ex) {
            Helper.error(this, ex.getMessage());
            ex.printStackTrace();
        }
    }
    
    private void refreshDetails() {
        if(selectedSales==null) return;
        try {
            LinkedList<SalesItem> salesItems = SalesItem.list(selectedSales.getId());
            String headers[] = {"Name", "Qty", "Price", "Discount", "Amount"};
            Object content[][] = new Object[salesItems.size()][headers.length];
            
            for(int i=0; i<salesItems.size(); i++) {
                SalesItem si = salesItems.get(i);
                content[i][0] = si.getStock().getItem().getName();
                content[i][1] = si.getQty();
                content[i][2] = String.format("%.2f", si.getPricePerQuantity());
                content[i][3] = String.format("%.2f", si.getDiscount());
                content[i][4] = String.format("%.2f", si.getFinalAmount());
            }
            
            DefaultTableModel model = new DefaultTableModel(content, headers) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }                
            };
            
            detailsTable.setModel(model);
            detailsTable.getColumnModel().getColumn(2).setCellRenderer(Helper.getRightRender());
            detailsTable.getColumnModel().getColumn(3).setCellRenderer(Helper.getRightRender());
            detailsTable.getColumnModel().getColumn(4).setCellRenderer(Helper.getRightRender());
        }catch(SQLException ex) {
            Helper.error(this, ex.getMessage());
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        fromField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        toField = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transaction History");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Semi-Condensed", 0, 24)); // NOI18N
        jLabel1.setText("Transaction History");

        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        userLabel.setText("User:");

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        salesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(salesTable);

        jLabel2.setText("From:");

        fromField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel3.setText("To:");

        toField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("DejaVu Sans Semi-Condensed", 0, 18)); // NOI18N
        jLabel4.setText("Transaction Details:");

        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(detailsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 712, Short.MAX_VALUE)
                        .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fromField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(0, 147, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fromField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(toField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        refreshTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesTableMouseClicked
        selectedSales = sales.get(salesTable.getSelectedRow());
        refreshDetails();
    }//GEN-LAST:event_salesTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable detailsTable;
    private javax.swing.JFormattedTextField fromField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable salesTable;
    private javax.swing.JFormattedTextField toField;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
